default: &default
  adapter: postgresql
  encoding: UTF-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("URL_SHORTERNER_DATABASE_HOST") { localhost } %>
  port: <%= ENV.fetch("URL_SHORTERNER_DATABASE_PORT") { 5432 } %>
  user: <%= ENV["URL_SHORTERNER_DATABASE_USER"] %>
  password: <%= ENV["URL_SHORTERNER_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: url_shorterner_development

test:
  <<: *default
  database: url_shorterner_test

production:
  <<: *default
  database: url_shorterner
